/**
 * Typing for the parser generated by `npm run compile:jison`
 * (see language.jison / language.jisonlex). The generated file is an
 * ES module produced by the `jison` CLI and postprocessed to pure ESM.
 */
export interface GeneratedLexer {
  setInput(input: string, yy?: unknown): void;
  /** Returns the next token's type name (e.g. 'CONTAINS', 'LIT', 'EOF'), or throws/returns falsy at end of input. */
  lex(): string | number;
  /** Raw matched text for the token just returned by lex(). */
  yytext: string;
  EOF?: number;
}

export interface GeneratedParser {
  /** Parses `input` per language.jison and returns the DSL source string. Throws on invalid input. */
  parse(input: string, ...args: any[]): string;
  /** The compiled lexer, also reused directly by tokenize.ts for TemplateProvider.addRule(). */
  lexer: GeneratedLexer;
  symbols_?: Record<string, number>;
  Parser: any;
  parser?: GeneratedParser;
}

export const parser: GeneratedParser;
export const Parser: any;
export const parse: (input: string, ...args: any[]) => string;
declare const language: GeneratedParser;
export default language;
