/**
 * Ambient typing for the parser generated by `npm run compile:jison`
 * (see language.jison / language.jisonlex). The generated file is a
 * plain CommonJS module produced by the `jison` CLI — it has no TS types
 * of its own, and (being generated + gitignored) may not exist on disk
 * until the compile:jison script has run at least once.
 */
declare module './language.generated.cjs' {
  interface GeneratedLexer {
    setInput(input: string, yy?: unknown): void;
    /** Returns the next token's type name (e.g. 'CONTAINS', 'LIT', 'EOF'), or throws/returns falsy at end of input. */
    lex(): string;
    /** Raw matched text for the token just returned by lex(). */
    yytext: string;
  }
  interface GeneratedParser {
    /** Parses `input` per language.jison and returns the DSL source string. Throws on invalid input. */
    parse(input: string): string;
    /** The compiled lexer, also reused directly by tokenize.ts for TemplateProvider.addRule(). */
    lexer: GeneratedLexer;
  }
  const parser: GeneratedParser;
  export default parser;
}
